export const _Image = {
    logo: "/image/icons/logo.png",
    icon: {
        zalo: "/image/icons/zalo.png",
        zalo_gray: "/image/icons/zalo-gray.png",
        phone: "/image/icons/phone.png",
        phone_gray: "/image/icons/phone-gray.png",
        bot_avatar: "/image/icons/bot_avatar.png",
        icon_1: "/image/icons/icon-01.png",
        icon_2: "/image/icons/icon-02.png",
        icon_3: "/image/icons/icon-03.png",
        icon_4: "/image/icons/icon-04.png",
        icon_send: "/image/icons/icon-send.png",
        icon_send_2: "/image/icons/icon-send-1.png",
        icon_mic: "/image/icons/icon-mic.png",
        icon_item_1: "/image/icons/icon-01.png",
        icon_item_2: "/image/icons/icon-02.png",
        icon_item_3: "/image/icons/icon-03.png",
        icon_item_4: "/image/icons/icon-04.png",
        icon_chat: "/image/icons/icon-chat.png",
        icon_headphone: "/image/icons/icon-phone.png",
        icon_arrow_right: "/image/icons/icon-arrow.png",
        icon_phone: "/image/icons/icon-phone.png",
        icon_phone_1: "/image/icons/icon-phone-1.png",
        icon_bar: "/image/icons/bar-icon.png",
        icon_arrow_left: "/image/icons/icon-arrow-left.png",
        icon_question: "/image/icons/icon-question.png",
        icon_hand: "/image/icons/hand.gif",
        icon_hand_1: "/image/icons/icon-hand-1.png",
        emoji: {
            emoji_1: "/image/icons/emoji/emoji-1.png",
            emoji_1_at: "/image/icons/emoji/emoji-1-at.png",
            emoji_2: "/image/icons/emoji/emoji-2.png",
            emoji_2_at: "/image/icons/emoji/emoji-2-at.png",
            emoji_3: "/image/icons/emoji/emoji-3.png",
            emoji_3_at: "/image/icons/emoji/emoji-3-at.png",
        },
        avt_user: "/image/icons/avt-user.png",
    },
};
